version: '3.8'

services:
  elasticsearch:
    container: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      # we added these both lines for allowing to run on http
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      #docker_port:localhost_port
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  #it is for viewing elasticsearch db
  kibana:
    container: kibana_for_elasticsearch
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

volumes:
  elasticsearch-data:
    driver: local